//! graphics tablet device
//!
//! The zwp_tablet_v2 interface represents one graphics tablet device. The
//! tablet interface itself does not generate events; all events are
//! generated by zwp_tablet_tool_v2 objects when in proximity above a tablet.
//!
//! A tablet has a number of static characteristics, e.g. device name and
//! pid/vid. These capabilities are sent in an event sequence after the
//! zwp_tablet_seat_v2.tablet_added event. This initial event sequence is
//! terminated by a zwp_tablet_v2.done event.

use crate::protocol_helpers::prelude::*;
use super::super::all_types::*;

/// A zwp_tablet_v2 object.
///
/// See the documentation of [the module][self] for the interface description.
pub struct ZwpTabletV2 {
    core: ObjectCore,
    handler: HandlerHolder<dyn ZwpTabletV2Handler>,
}

struct DefaultHandler;

impl ZwpTabletV2Handler for DefaultHandler { }

impl ConcreteObject for ZwpTabletV2 {
    const XML_VERSION: u32 = 2;
    const INTERFACE: ObjectInterface = ObjectInterface::ZwpTabletV2;
    const INTERFACE_NAME: &str = "zwp_tablet_v2";
}

impl ZwpTabletV2 {
    /// Sets a new handler.
    pub fn set_handler(&self, handler: impl ZwpTabletV2Handler) {
        self.set_boxed_handler(Box::new(handler));
    }

    /// Sets a new, already boxed handler.
    pub fn set_boxed_handler(&self, handler: Box<dyn ZwpTabletV2Handler>) {
        if self.core.state.destroyed.get() {
            return;
        }
        self.handler.set(Some(handler));
    }
}

impl Debug for ZwpTabletV2 {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ZwpTabletV2")
            .field("server_obj_id", &self.core.server_obj_id.get())
            .field("client_id", &self.core.client_id.get())
            .field("client_obj_id", &self.core.client_obj_id.get())
            .finish()
    }
}

impl ZwpTabletV2 {
    /// Since when the destroy message is available.
    pub const MSG__DESTROY__SINCE: u32 = 1;

    /// destroy the tablet object
    ///
    /// This destroys the client's resource for this tablet object.
    #[inline]
    pub fn try_send_destroy(
        &self,
    ) -> Result<(), ObjectError> {
        let core = self.core();
        let Some(id) = core.server_obj_id.get() else {
            return Err(ObjectError(ObjectErrorKind::ReceiverNoServerId));
        };
        #[cfg(feature = "logging")]
        if self.core.state.log {
            #[cold]
            fn log(state: &State, id: u32) {
                let (millis, micros) = time_since_epoch();
                let prefix = &state.log_prefix;
                let args = format_args!("[{millis:7}.{micros:03}] {prefix}server      <= zwp_tablet_v2#{}.destroy()\n", id);
                state.log(args);
            }
            log(&self.core.state, id);
        }
        let Some(endpoint) = &self.core.state.server else {
            return Ok(());
        };
        if !endpoint.flush_queued.replace(true) {
            self.core.state.add_flushable_endpoint(endpoint, None);
        }
        let mut outgoing_ref = endpoint.outgoing.borrow_mut();
        let outgoing = &mut *outgoing_ref;
        let mut fmt = outgoing.formatter();
        fmt.words([
            id,
            0,
        ]);
        Ok(())
    }

    /// destroy the tablet object
    ///
    /// This destroys the client's resource for this tablet object.
    #[inline]
    pub fn send_destroy(
        &self,
    ) {
        let res = self.try_send_destroy(
        );
        if let Err(e) = res {
            log_send("zwp_tablet_v2.destroy", &e);
        }
    }

    /// Since when the name message is available.
    pub const MSG__NAME__SINCE: u32 = 1;

    /// tablet device name
    ///
    /// A descriptive name for the tablet device.
    ///
    /// If the device has no descriptive name, this event is not sent.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    ///
    /// # Arguments
    ///
    /// - `name`: the device name
    #[inline]
    pub fn try_send_name(
        &self,
        name: &str,
    ) -> Result<(), ObjectError> {
        let (
            arg0,
        ) = (
            name,
        );
        let core = self.core();
        let client_ref = core.client.borrow();
        let Some(client) = &*client_ref else {
            return Err(ObjectError(ObjectErrorKind::ReceiverNoClient));
        };
        let id = core.client_obj_id.get().unwrap_or(0);
        #[cfg(feature = "logging")]
        if self.core.state.log {
            #[cold]
            fn log(state: &State, client_id: u64, id: u32, arg0: &str) {
                let (millis, micros) = time_since_epoch();
                let prefix = &state.log_prefix;
                let args = format_args!("[{millis:7}.{micros:03}] {prefix}client#{:<4} <= zwp_tablet_v2#{}.name(name: {:?})\n", client_id, id, arg0);
                state.log(args);
            }
            log(&self.core.state, client.endpoint.id, id, arg0);
        }
        let endpoint = &client.endpoint;
        if !endpoint.flush_queued.replace(true) {
            self.core.state.add_flushable_endpoint(endpoint, Some(client));
        }
        let mut outgoing_ref = endpoint.outgoing.borrow_mut();
        let outgoing = &mut *outgoing_ref;
        let mut fmt = outgoing.formatter();
        fmt.words([
            id,
            0,
        ]);
        fmt.string(arg0);
        Ok(())
    }

    /// tablet device name
    ///
    /// A descriptive name for the tablet device.
    ///
    /// If the device has no descriptive name, this event is not sent.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    ///
    /// # Arguments
    ///
    /// - `name`: the device name
    #[inline]
    pub fn send_name(
        &self,
        name: &str,
    ) {
        let res = self.try_send_name(
            name,
        );
        if let Err(e) = res {
            log_send("zwp_tablet_v2.name", &e);
        }
    }

    /// Since when the id message is available.
    pub const MSG__ID__SINCE: u32 = 1;

    /// tablet device vendor/product id
    ///
    /// The vendor and product IDs for the tablet device.
    ///
    /// The interpretation of the id depends on the zwp_tablet_v2.bustype.
    /// Prior to version v2 of this protocol, the id was implied to be a USB
    /// vendor and product ID. If no zwp_tablet_v2.bustype is sent, the ID
    /// is to be interpreted as USB vendor and product ID.
    ///
    /// If the device has no vendor/product ID, this event is not sent.
    /// This can happen for virtual devices or non-USB devices, for instance.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    ///
    /// # Arguments
    ///
    /// - `vid`: vendor id
    /// - `pid`: product id
    #[inline]
    pub fn try_send_id(
        &self,
        vid: u32,
        pid: u32,
    ) -> Result<(), ObjectError> {
        let (
            arg0,
            arg1,
        ) = (
            vid,
            pid,
        );
        let core = self.core();
        let client_ref = core.client.borrow();
        let Some(client) = &*client_ref else {
            return Err(ObjectError(ObjectErrorKind::ReceiverNoClient));
        };
        let id = core.client_obj_id.get().unwrap_or(0);
        #[cfg(feature = "logging")]
        if self.core.state.log {
            #[cold]
            fn log(state: &State, client_id: u64, id: u32, arg0: u32, arg1: u32) {
                let (millis, micros) = time_since_epoch();
                let prefix = &state.log_prefix;
                let args = format_args!("[{millis:7}.{micros:03}] {prefix}client#{:<4} <= zwp_tablet_v2#{}.id(vid: {}, pid: {})\n", client_id, id, arg0, arg1);
                state.log(args);
            }
            log(&self.core.state, client.endpoint.id, id, arg0, arg1);
        }
        let endpoint = &client.endpoint;
        if !endpoint.flush_queued.replace(true) {
            self.core.state.add_flushable_endpoint(endpoint, Some(client));
        }
        let mut outgoing_ref = endpoint.outgoing.borrow_mut();
        let outgoing = &mut *outgoing_ref;
        let mut fmt = outgoing.formatter();
        fmt.words([
            id,
            1,
            arg0,
            arg1,
        ]);
        Ok(())
    }

    /// tablet device vendor/product id
    ///
    /// The vendor and product IDs for the tablet device.
    ///
    /// The interpretation of the id depends on the zwp_tablet_v2.bustype.
    /// Prior to version v2 of this protocol, the id was implied to be a USB
    /// vendor and product ID. If no zwp_tablet_v2.bustype is sent, the ID
    /// is to be interpreted as USB vendor and product ID.
    ///
    /// If the device has no vendor/product ID, this event is not sent.
    /// This can happen for virtual devices or non-USB devices, for instance.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    ///
    /// # Arguments
    ///
    /// - `vid`: vendor id
    /// - `pid`: product id
    #[inline]
    pub fn send_id(
        &self,
        vid: u32,
        pid: u32,
    ) {
        let res = self.try_send_id(
            vid,
            pid,
        );
        if let Err(e) = res {
            log_send("zwp_tablet_v2.id", &e);
        }
    }

    /// Since when the path message is available.
    pub const MSG__PATH__SINCE: u32 = 1;

    /// path to the device
    ///
    /// A system-specific device path that indicates which device is behind
    /// this zwp_tablet_v2. This information may be used to gather additional
    /// information about the device, e.g. through libwacom.
    ///
    /// A device may have more than one device path. If so, multiple
    /// zwp_tablet_v2.path events are sent. A device may be emulated and not
    /// have a device path, and in that case this event will not be sent.
    ///
    /// The format of the path is unspecified, it may be a device node, a
    /// sysfs path, or some other identifier. It is up to the client to
    /// identify the string provided.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    ///
    /// # Arguments
    ///
    /// - `path`: path to local device
    #[inline]
    pub fn try_send_path(
        &self,
        path: &str,
    ) -> Result<(), ObjectError> {
        let (
            arg0,
        ) = (
            path,
        );
        let core = self.core();
        let client_ref = core.client.borrow();
        let Some(client) = &*client_ref else {
            return Err(ObjectError(ObjectErrorKind::ReceiverNoClient));
        };
        let id = core.client_obj_id.get().unwrap_or(0);
        #[cfg(feature = "logging")]
        if self.core.state.log {
            #[cold]
            fn log(state: &State, client_id: u64, id: u32, arg0: &str) {
                let (millis, micros) = time_since_epoch();
                let prefix = &state.log_prefix;
                let args = format_args!("[{millis:7}.{micros:03}] {prefix}client#{:<4} <= zwp_tablet_v2#{}.path(path: {:?})\n", client_id, id, arg0);
                state.log(args);
            }
            log(&self.core.state, client.endpoint.id, id, arg0);
        }
        let endpoint = &client.endpoint;
        if !endpoint.flush_queued.replace(true) {
            self.core.state.add_flushable_endpoint(endpoint, Some(client));
        }
        let mut outgoing_ref = endpoint.outgoing.borrow_mut();
        let outgoing = &mut *outgoing_ref;
        let mut fmt = outgoing.formatter();
        fmt.words([
            id,
            2,
        ]);
        fmt.string(arg0);
        Ok(())
    }

    /// path to the device
    ///
    /// A system-specific device path that indicates which device is behind
    /// this zwp_tablet_v2. This information may be used to gather additional
    /// information about the device, e.g. through libwacom.
    ///
    /// A device may have more than one device path. If so, multiple
    /// zwp_tablet_v2.path events are sent. A device may be emulated and not
    /// have a device path, and in that case this event will not be sent.
    ///
    /// The format of the path is unspecified, it may be a device node, a
    /// sysfs path, or some other identifier. It is up to the client to
    /// identify the string provided.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    ///
    /// # Arguments
    ///
    /// - `path`: path to local device
    #[inline]
    pub fn send_path(
        &self,
        path: &str,
    ) {
        let res = self.try_send_path(
            path,
        );
        if let Err(e) = res {
            log_send("zwp_tablet_v2.path", &e);
        }
    }

    /// Since when the done message is available.
    pub const MSG__DONE__SINCE: u32 = 1;

    /// tablet description events sequence complete
    ///
    /// This event is sent immediately to signal the end of the initial
    /// burst of descriptive events. A client may consider the static
    /// description of the tablet to be complete and finalize initialization
    /// of the tablet.
    #[inline]
    pub fn try_send_done(
        &self,
    ) -> Result<(), ObjectError> {
        let core = self.core();
        let client_ref = core.client.borrow();
        let Some(client) = &*client_ref else {
            return Err(ObjectError(ObjectErrorKind::ReceiverNoClient));
        };
        let id = core.client_obj_id.get().unwrap_or(0);
        #[cfg(feature = "logging")]
        if self.core.state.log {
            #[cold]
            fn log(state: &State, client_id: u64, id: u32) {
                let (millis, micros) = time_since_epoch();
                let prefix = &state.log_prefix;
                let args = format_args!("[{millis:7}.{micros:03}] {prefix}client#{:<4} <= zwp_tablet_v2#{}.done()\n", client_id, id);
                state.log(args);
            }
            log(&self.core.state, client.endpoint.id, id);
        }
        let endpoint = &client.endpoint;
        if !endpoint.flush_queued.replace(true) {
            self.core.state.add_flushable_endpoint(endpoint, Some(client));
        }
        let mut outgoing_ref = endpoint.outgoing.borrow_mut();
        let outgoing = &mut *outgoing_ref;
        let mut fmt = outgoing.formatter();
        fmt.words([
            id,
            3,
        ]);
        Ok(())
    }

    /// tablet description events sequence complete
    ///
    /// This event is sent immediately to signal the end of the initial
    /// burst of descriptive events. A client may consider the static
    /// description of the tablet to be complete and finalize initialization
    /// of the tablet.
    #[inline]
    pub fn send_done(
        &self,
    ) {
        let res = self.try_send_done(
        );
        if let Err(e) = res {
            log_send("zwp_tablet_v2.done", &e);
        }
    }

    /// Since when the removed message is available.
    pub const MSG__REMOVED__SINCE: u32 = 1;

    /// tablet removed event
    ///
    /// Sent when the tablet has been removed from the system. When a tablet
    /// is removed, some tools may be removed.
    ///
    /// When this event is received, the client must zwp_tablet_v2.destroy
    /// the object.
    #[inline]
    pub fn try_send_removed(
        &self,
    ) -> Result<(), ObjectError> {
        let core = self.core();
        let client_ref = core.client.borrow();
        let Some(client) = &*client_ref else {
            return Err(ObjectError(ObjectErrorKind::ReceiverNoClient));
        };
        let id = core.client_obj_id.get().unwrap_or(0);
        #[cfg(feature = "logging")]
        if self.core.state.log {
            #[cold]
            fn log(state: &State, client_id: u64, id: u32) {
                let (millis, micros) = time_since_epoch();
                let prefix = &state.log_prefix;
                let args = format_args!("[{millis:7}.{micros:03}] {prefix}client#{:<4} <= zwp_tablet_v2#{}.removed()\n", client_id, id);
                state.log(args);
            }
            log(&self.core.state, client.endpoint.id, id);
        }
        let endpoint = &client.endpoint;
        if !endpoint.flush_queued.replace(true) {
            self.core.state.add_flushable_endpoint(endpoint, Some(client));
        }
        let mut outgoing_ref = endpoint.outgoing.borrow_mut();
        let outgoing = &mut *outgoing_ref;
        let mut fmt = outgoing.formatter();
        fmt.words([
            id,
            4,
        ]);
        Ok(())
    }

    /// tablet removed event
    ///
    /// Sent when the tablet has been removed from the system. When a tablet
    /// is removed, some tools may be removed.
    ///
    /// When this event is received, the client must zwp_tablet_v2.destroy
    /// the object.
    #[inline]
    pub fn send_removed(
        &self,
    ) {
        let res = self.try_send_removed(
        );
        if let Err(e) = res {
            log_send("zwp_tablet_v2.removed", &e);
        }
    }

    /// Since when the bustype message is available.
    pub const MSG__BUSTYPE__SINCE: u32 = 2;

    /// tablet device bus type
    ///
    /// The bustype argument is one of the BUS_ defines in the Linux kernel's
    /// linux/input.h
    ///
    /// If the device has no known bustype or the bustype cannot be
    /// queried, this event is not sent.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    ///
    /// # Arguments
    ///
    /// - `bustype`: bus type
    #[inline]
    pub fn try_send_bustype(
        &self,
        bustype: ZwpTabletV2Bustype,
    ) -> Result<(), ObjectError> {
        let (
            arg0,
        ) = (
            bustype,
        );
        let core = self.core();
        let client_ref = core.client.borrow();
        let Some(client) = &*client_ref else {
            return Err(ObjectError(ObjectErrorKind::ReceiverNoClient));
        };
        let id = core.client_obj_id.get().unwrap_or(0);
        #[cfg(feature = "logging")]
        if self.core.state.log {
            #[cold]
            fn log(state: &State, client_id: u64, id: u32, arg0: ZwpTabletV2Bustype) {
                let (millis, micros) = time_since_epoch();
                let prefix = &state.log_prefix;
                let args = format_args!("[{millis:7}.{micros:03}] {prefix}client#{:<4} <= zwp_tablet_v2#{}.bustype(bustype: {:?})\n", client_id, id, arg0);
                state.log(args);
            }
            log(&self.core.state, client.endpoint.id, id, arg0);
        }
        let endpoint = &client.endpoint;
        if !endpoint.flush_queued.replace(true) {
            self.core.state.add_flushable_endpoint(endpoint, Some(client));
        }
        let mut outgoing_ref = endpoint.outgoing.borrow_mut();
        let outgoing = &mut *outgoing_ref;
        let mut fmt = outgoing.formatter();
        fmt.words([
            id,
            5,
            arg0.0,
        ]);
        Ok(())
    }

    /// tablet device bus type
    ///
    /// The bustype argument is one of the BUS_ defines in the Linux kernel's
    /// linux/input.h
    ///
    /// If the device has no known bustype or the bustype cannot be
    /// queried, this event is not sent.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    ///
    /// # Arguments
    ///
    /// - `bustype`: bus type
    #[inline]
    pub fn send_bustype(
        &self,
        bustype: ZwpTabletV2Bustype,
    ) {
        let res = self.try_send_bustype(
            bustype,
        );
        if let Err(e) = res {
            log_send("zwp_tablet_v2.bustype", &e);
        }
    }
}

/// A message handler for [`ZwpTabletV2`] proxies.
pub trait ZwpTabletV2Handler: Any {
    /// Event handler for wl_display.delete_id messages deleting the ID of this object.
    ///
    /// The default handler forwards the event to the client, if any.
    #[inline]
    fn delete_id(&mut self, slf: &Rc<ZwpTabletV2>) {
        slf.core.delete_id();
    }

    /// destroy the tablet object
    ///
    /// This destroys the client's resource for this tablet object.
    #[inline]
    fn handle_destroy(
        &mut self,
        slf: &Rc<ZwpTabletV2>,
    ) {
        if !slf.core.forward_to_server.get() {
            return;
        }
        let res = slf.try_send_destroy(
        );
        if let Err(e) = res {
            log_forward("zwp_tablet_v2.destroy", &e);
        }
    }

    /// tablet device name
    ///
    /// A descriptive name for the tablet device.
    ///
    /// If the device has no descriptive name, this event is not sent.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    ///
    /// # Arguments
    ///
    /// - `name`: the device name
    #[inline]
    fn handle_name(
        &mut self,
        slf: &Rc<ZwpTabletV2>,
        name: &str,
    ) {
        if !slf.core.forward_to_client.get() {
            return;
        }
        let res = slf.try_send_name(
            name,
        );
        if let Err(e) = res {
            log_forward("zwp_tablet_v2.name", &e);
        }
    }

    /// tablet device vendor/product id
    ///
    /// The vendor and product IDs for the tablet device.
    ///
    /// The interpretation of the id depends on the zwp_tablet_v2.bustype.
    /// Prior to version v2 of this protocol, the id was implied to be a USB
    /// vendor and product ID. If no zwp_tablet_v2.bustype is sent, the ID
    /// is to be interpreted as USB vendor and product ID.
    ///
    /// If the device has no vendor/product ID, this event is not sent.
    /// This can happen for virtual devices or non-USB devices, for instance.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    ///
    /// # Arguments
    ///
    /// - `vid`: vendor id
    /// - `pid`: product id
    #[inline]
    fn handle_id(
        &mut self,
        slf: &Rc<ZwpTabletV2>,
        vid: u32,
        pid: u32,
    ) {
        if !slf.core.forward_to_client.get() {
            return;
        }
        let res = slf.try_send_id(
            vid,
            pid,
        );
        if let Err(e) = res {
            log_forward("zwp_tablet_v2.id", &e);
        }
    }

    /// path to the device
    ///
    /// A system-specific device path that indicates which device is behind
    /// this zwp_tablet_v2. This information may be used to gather additional
    /// information about the device, e.g. through libwacom.
    ///
    /// A device may have more than one device path. If so, multiple
    /// zwp_tablet_v2.path events are sent. A device may be emulated and not
    /// have a device path, and in that case this event will not be sent.
    ///
    /// The format of the path is unspecified, it may be a device node, a
    /// sysfs path, or some other identifier. It is up to the client to
    /// identify the string provided.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    ///
    /// # Arguments
    ///
    /// - `path`: path to local device
    #[inline]
    fn handle_path(
        &mut self,
        slf: &Rc<ZwpTabletV2>,
        path: &str,
    ) {
        if !slf.core.forward_to_client.get() {
            return;
        }
        let res = slf.try_send_path(
            path,
        );
        if let Err(e) = res {
            log_forward("zwp_tablet_v2.path", &e);
        }
    }

    /// tablet description events sequence complete
    ///
    /// This event is sent immediately to signal the end of the initial
    /// burst of descriptive events. A client may consider the static
    /// description of the tablet to be complete and finalize initialization
    /// of the tablet.
    #[inline]
    fn handle_done(
        &mut self,
        slf: &Rc<ZwpTabletV2>,
    ) {
        if !slf.core.forward_to_client.get() {
            return;
        }
        let res = slf.try_send_done(
        );
        if let Err(e) = res {
            log_forward("zwp_tablet_v2.done", &e);
        }
    }

    /// tablet removed event
    ///
    /// Sent when the tablet has been removed from the system. When a tablet
    /// is removed, some tools may be removed.
    ///
    /// When this event is received, the client must zwp_tablet_v2.destroy
    /// the object.
    #[inline]
    fn handle_removed(
        &mut self,
        slf: &Rc<ZwpTabletV2>,
    ) {
        if !slf.core.forward_to_client.get() {
            return;
        }
        let res = slf.try_send_removed(
        );
        if let Err(e) = res {
            log_forward("zwp_tablet_v2.removed", &e);
        }
    }

    /// tablet device bus type
    ///
    /// The bustype argument is one of the BUS_ defines in the Linux kernel's
    /// linux/input.h
    ///
    /// If the device has no known bustype or the bustype cannot be
    /// queried, this event is not sent.
    ///
    /// This event is sent in the initial burst of events before the
    /// zwp_tablet_v2.done event.
    ///
    /// # Arguments
    ///
    /// - `bustype`: bus type
    #[inline]
    fn handle_bustype(
        &mut self,
        slf: &Rc<ZwpTabletV2>,
        bustype: ZwpTabletV2Bustype,
    ) {
        if !slf.core.forward_to_client.get() {
            return;
        }
        let res = slf.try_send_bustype(
            bustype,
        );
        if let Err(e) = res {
            log_forward("zwp_tablet_v2.bustype", &e);
        }
    }
}

impl ObjectPrivate for ZwpTabletV2 {
    fn new(state: &Rc<State>, version: u32) -> Rc<Self> {
        Rc::<Self>::new_cyclic(|slf| Self {
            core: ObjectCore::new(state, slf.clone(), ObjectInterface::ZwpTabletV2, version),
            handler: Default::default(),
        })
    }

    fn delete_id(self: Rc<Self>) -> Result<(), (ObjectError, Rc<dyn Object>)> {
        let Some(mut handler) = self.handler.try_borrow_mut() else {
            return Err((ObjectError(ObjectErrorKind::HandlerBorrowed), self));
        };
        if let Some(handler) = &mut *handler {
            handler.delete_id(&self);
        } else {
            self.core.delete_id();
        }
        Ok(())
    }

    fn handle_request(self: Rc<Self>, client: &Rc<Client>, msg: &[u32], fds: &mut VecDeque<Rc<OwnedFd>>) -> Result<(), ObjectError> {
        let Some(mut handler) = self.handler.try_borrow_mut() else {
            return Err(ObjectError(ObjectErrorKind::HandlerBorrowed));
        };
        let handler = &mut *handler;
        match msg[1] & 0xffff {
            0 => {
                if msg.len() != 2 {
                    return Err(ObjectError(ObjectErrorKind::WrongMessageSize(msg.len() as u32 * 4, 8)));
                }
                #[cfg(feature = "logging")]
                if self.core.state.log {
                    #[cold]
                    fn log(state: &State, client_id: u64, id: u32) {
                        let (millis, micros) = time_since_epoch();
                        let prefix = &state.log_prefix;
                        let args = format_args!("[{millis:7}.{micros:03}] {prefix}client#{:<4} -> zwp_tablet_v2#{}.destroy()\n", client_id, id);
                        state.log(args);
                    }
                    log(&self.core.state, client.endpoint.id, msg[0]);
                }
                self.core.handle_client_destroy();
                if let Some(handler) = handler {
                    (**handler).handle_destroy(&self);
                } else {
                    DefaultHandler.handle_destroy(&self);
                }
            }
            n => {
                let _ = client;
                let _ = msg;
                let _ = fds;
                let _ = handler;
                return Err(ObjectError(ObjectErrorKind::UnknownMessageId(n)));
            }
        }
        Ok(())
    }

    fn handle_event(self: Rc<Self>, server: &Endpoint, msg: &[u32], fds: &mut VecDeque<Rc<OwnedFd>>) -> Result<(), ObjectError> {
        let Some(mut handler) = self.handler.try_borrow_mut() else {
            return Err(ObjectError(ObjectErrorKind::HandlerBorrowed));
        };
        let handler = &mut *handler;
        match msg[1] & 0xffff {
            0 => {
                let mut offset = 2;
                let arg0;
                (arg0, offset) = parse_string::<NonNullString>(msg, offset, "name")?;
                if offset != msg.len() {
                    return Err(ObjectError(ObjectErrorKind::TrailingBytes));
                }
                #[cfg(feature = "logging")]
                if self.core.state.log {
                    #[cold]
                    fn log(state: &State, id: u32, arg0: &str) {
                        let (millis, micros) = time_since_epoch();
                        let prefix = &state.log_prefix;
                        let args = format_args!("[{millis:7}.{micros:03}] {prefix}server      -> zwp_tablet_v2#{}.name(name: {:?})\n", id, arg0);
                        state.log(args);
                    }
                    log(&self.core.state, msg[0], arg0);
                }
                if let Some(handler) = handler {
                    (**handler).handle_name(&self, arg0);
                } else {
                    DefaultHandler.handle_name(&self, arg0);
                }
            }
            1 => {
                let [
                    arg0,
                    arg1,
                ] = msg[2..] else {
                    return Err(ObjectError(ObjectErrorKind::WrongMessageSize(msg.len() as u32 * 4, 16)));
                };
                #[cfg(feature = "logging")]
                if self.core.state.log {
                    #[cold]
                    fn log(state: &State, id: u32, arg0: u32, arg1: u32) {
                        let (millis, micros) = time_since_epoch();
                        let prefix = &state.log_prefix;
                        let args = format_args!("[{millis:7}.{micros:03}] {prefix}server      -> zwp_tablet_v2#{}.id(vid: {}, pid: {})\n", id, arg0, arg1);
                        state.log(args);
                    }
                    log(&self.core.state, msg[0], arg0, arg1);
                }
                if let Some(handler) = handler {
                    (**handler).handle_id(&self, arg0, arg1);
                } else {
                    DefaultHandler.handle_id(&self, arg0, arg1);
                }
            }
            2 => {
                let mut offset = 2;
                let arg0;
                (arg0, offset) = parse_string::<NonNullString>(msg, offset, "path")?;
                if offset != msg.len() {
                    return Err(ObjectError(ObjectErrorKind::TrailingBytes));
                }
                #[cfg(feature = "logging")]
                if self.core.state.log {
                    #[cold]
                    fn log(state: &State, id: u32, arg0: &str) {
                        let (millis, micros) = time_since_epoch();
                        let prefix = &state.log_prefix;
                        let args = format_args!("[{millis:7}.{micros:03}] {prefix}server      -> zwp_tablet_v2#{}.path(path: {:?})\n", id, arg0);
                        state.log(args);
                    }
                    log(&self.core.state, msg[0], arg0);
                }
                if let Some(handler) = handler {
                    (**handler).handle_path(&self, arg0);
                } else {
                    DefaultHandler.handle_path(&self, arg0);
                }
            }
            3 => {
                if msg.len() != 2 {
                    return Err(ObjectError(ObjectErrorKind::WrongMessageSize(msg.len() as u32 * 4, 8)));
                }
                #[cfg(feature = "logging")]
                if self.core.state.log {
                    #[cold]
                    fn log(state: &State, id: u32) {
                        let (millis, micros) = time_since_epoch();
                        let prefix = &state.log_prefix;
                        let args = format_args!("[{millis:7}.{micros:03}] {prefix}server      -> zwp_tablet_v2#{}.done()\n", id);
                        state.log(args);
                    }
                    log(&self.core.state, msg[0]);
                }
                if let Some(handler) = handler {
                    (**handler).handle_done(&self);
                } else {
                    DefaultHandler.handle_done(&self);
                }
            }
            4 => {
                if msg.len() != 2 {
                    return Err(ObjectError(ObjectErrorKind::WrongMessageSize(msg.len() as u32 * 4, 8)));
                }
                #[cfg(feature = "logging")]
                if self.core.state.log {
                    #[cold]
                    fn log(state: &State, id: u32) {
                        let (millis, micros) = time_since_epoch();
                        let prefix = &state.log_prefix;
                        let args = format_args!("[{millis:7}.{micros:03}] {prefix}server      -> zwp_tablet_v2#{}.removed()\n", id);
                        state.log(args);
                    }
                    log(&self.core.state, msg[0]);
                }
                if let Some(handler) = handler {
                    (**handler).handle_removed(&self);
                } else {
                    DefaultHandler.handle_removed(&self);
                }
            }
            5 => {
                let [
                    arg0,
                ] = msg[2..] else {
                    return Err(ObjectError(ObjectErrorKind::WrongMessageSize(msg.len() as u32 * 4, 12)));
                };
                let arg0 = ZwpTabletV2Bustype(arg0);
                #[cfg(feature = "logging")]
                if self.core.state.log {
                    #[cold]
                    fn log(state: &State, id: u32, arg0: ZwpTabletV2Bustype) {
                        let (millis, micros) = time_since_epoch();
                        let prefix = &state.log_prefix;
                        let args = format_args!("[{millis:7}.{micros:03}] {prefix}server      -> zwp_tablet_v2#{}.bustype(bustype: {:?})\n", id, arg0);
                        state.log(args);
                    }
                    log(&self.core.state, msg[0], arg0);
                }
                if let Some(handler) = handler {
                    (**handler).handle_bustype(&self, arg0);
                } else {
                    DefaultHandler.handle_bustype(&self, arg0);
                }
            }
            n => {
                let _ = server;
                let _ = msg;
                let _ = fds;
                let _ = handler;
                return Err(ObjectError(ObjectErrorKind::UnknownMessageId(n)));
            }
        }
        Ok(())
    }

    fn get_request_name(&self, id: u32) -> Option<&'static str> {
        let name = match id {
            0 => "destroy",
            _ => return None,
        };
        Some(name)
    }

    fn get_event_name(&self, id: u32) -> Option<&'static str> {
        let name = match id {
            0 => "name",
            1 => "id",
            2 => "path",
            3 => "done",
            4 => "removed",
            5 => "bustype",
            _ => return None,
        };
        Some(name)
    }
}

impl Object for ZwpTabletV2 {
    fn core(&self) -> &ObjectCore {
        &self.core
    }

    fn unset_handler(&self) {
        self.handler.set(None);
    }

    fn get_handler_any_ref(&self) -> Result<HandlerRef<'_, dyn Any>, HandlerAccessError> {
        let borrowed = self.handler.try_borrow().ok_or(HandlerAccessError::AlreadyBorrowed)?;
        if borrowed.is_none() {
            return Err(HandlerAccessError::NoHandler);
        }
        Ok(HandlerRef::map(borrowed, |handler| &**handler.as_ref().unwrap() as &dyn Any))
    }

    fn get_handler_any_mut(&self) -> Result<HandlerMut<'_, dyn Any>, HandlerAccessError> {
        let borrowed = self.handler.try_borrow_mut().ok_or(HandlerAccessError::AlreadyBorrowed)?;
        if borrowed.is_none() {
            return Err(HandlerAccessError::NoHandler);
        }
        Ok(HandlerMut::map(borrowed, |handler| &mut **handler.as_mut().unwrap() as &mut dyn Any))
    }
}

impl ZwpTabletV2 {
    /// Since when the bustype.usb enum variant is available.
    pub const ENM__BUSTYPE_USB__SINCE: u32 = 1;
    /// Since when the bustype.bluetooth enum variant is available.
    pub const ENM__BUSTYPE_BLUETOOTH__SINCE: u32 = 1;
    /// Since when the bustype.virtual enum variant is available.
    pub const ENM__BUSTYPE_VIRTUAL__SINCE: u32 = 1;
    /// Since when the bustype.serial enum variant is available.
    pub const ENM__BUSTYPE_SERIAL__SINCE: u32 = 1;
    /// Since when the bustype.i2c enum variant is available.
    pub const ENM__BUSTYPE_I2C__SINCE: u32 = 1;
}

/// bus type 
///
/// Describes the bus types this tablet is connected to.
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub struct ZwpTabletV2Bustype(pub u32);

impl ZwpTabletV2Bustype {
    /// USB
    pub const USB: Self = Self(3);

    /// Bluetooth
    pub const BLUETOOTH: Self = Self(5);

    /// Virtual
    pub const VIRTUAL: Self = Self(6);

    /// Serial
    pub const SERIAL: Self = Self(17);

    /// I2C
    pub const I2C: Self = Self(24);
}

impl Debug for ZwpTabletV2Bustype {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        let name = match *self {
            Self::USB => "USB",
            Self::BLUETOOTH => "BLUETOOTH",
            Self::VIRTUAL => "VIRTUAL",
            Self::SERIAL => "SERIAL",
            Self::I2C => "I2C",
            _ => return Debug::fmt(&self.0, f),
        };
        f.write_str(name)
    }
}
